### ISSUE TITLE
Python error when I run protonup

### ISSUE THREAD

**Issue by coreybruce** [AUNaseef/protonup#23]
Hi just wanted to inform you of a bug I am having, I am using the protonup-git aur package on Manjaro and when I now run protonup I get this error

```
Traceback (most recent call last):
  File "/usr/bin/protonup", line 33, in <module>
    sys.exit(load_entry_point('protonup==0.1.4', 'console_scripts', 'protonup')())
  File "/usr/bin/protonup", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for protonup

```

**Comment by AUNaseef** [comment]
I don't maintain the protonup package on AUR, if anyone still have this issue please reach out to whoever maintains that version or install protonup through PIP.
