### ISSUE TITLE
TypeError: when running protonup --releases

### ISSUE THREAD

**Issue by ace510** [AUNaseef/protonup#42]
Steps to reproduce:

1. python 3.12.3
2. pip install protonup
3. run protonup --releases

expected result: view proton releasese

actual result
`protonup --releases
Traceback (most recent call last):
  File "/home/cetadmin/.local/bin/protonup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cetadmin/.local/share/pipx/venvs/protonup/lib/python3.12/site-packages/protonup/__init__.py", line 4, in main
    return main()
           ^^^^^^
  File "/home/cetadmin/.local/share/pipx/venvs/protonup/lib/python3.12/site-packages/protonup/cli.py", line 47, in main
    for tag in fetch_releases():
               ^^^^^^^^^^^^^^^^
  File "/home/cetadmin/.local/share/pipx/venvs/protonup/lib/python3.12/site-packages/protonup/api.py", line 41, in fetch_releases
    tags.append(release['tag_name'])
                ~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'`

OS: Fedora
Python 3.12.3

**Comment by xz-dev** [comment]
Due to Github API speed limit
